"""Store for constant objects"""

_column_name_dict = {
    ## for global metadata header of api 101
    244: "GP_CODE",
    245: "ITYP",
    246: "INR",
    247: "Zusatz",
    250: "Datum",
    252: "Art",
    249: "Betreff",
    248: "Zitation",
    # 251: "Datum (Sort),DATUMSORT",
    253: "Phasen",
    254: "Status",
    255: "Doktyp",
    # 256: "Zustimmung_aktiv",  # so far always "ZZZZ"
    257: "Doktyp_Lang",
    258: "HIS_URL",  # Geschichtsseite_Url,
    # 259: "RSS",
    # 260: "DATUM_VON",
    261: "VHG",
    262: "VHG2",
    # 321: "LZ-Buttons",
    341: "Personen_ID",
    342: "Fraktionen",
    343: "Thema",
    344: "Schlagwort",
    345: "EuroVoc",
    # 1281: "sysdate???,",
    # 821: "WENTRY_ID",
    # 1821: "INRNUM,INRNUM",
    # 2011: "NRGP,GP_CODE",
    2012: "Gremium",
    382: "Gruppe",
    # below are not yet exported (server side)
    # 201: "Abstimmung 3. Lesung,VOTE",
    # 202: "Dafür,VOTE_YES",
    # 203: "Dagegen,VOTE_NO",
    # 703: "Abstimmungstext,VOTE_TEXT",
    # 704: "Abstimmungskommentar,VOTE_COMMENT",
    ## for global metadata header of api 211
    2701: "Datum",  # "Datum der Sitzung (dd.mm.yyyy)",
    2710: "HIS_URL",  # "Verlinkung auf die Geschichtsseite der Sitzung",
    2702: "Periode",  # "Gesetzgebungsperiode in römischen Ziffern",
    2703: "Gremium",  # "NRSITZ (Nationalrat) oder BRSITZ (Bundesrat)",
    2704: "Nummer",  # "Nummer der Sitzung",
    2705: "Kurztitel",  # "Kurztitel der Sitzung",
    2713: "Zitation",  # "Zitation der Sitzung",
    2706: "Art",  # "Art der Sitzung"
    2707: "Plenar_Sitzung",  # "Plenar-Sitzung"
    # 2708: "Datum", #Datum der Sitzung (yyyy-mm-dd),
    # 2709: "Verlinkung auf Dokumente der Stenographischen Protokolle (PDF, HTML) in strukturierter HTML-Darstellung", #"Verlinkung auf Dokumente der Stenographischen Protokolle (PDF, HTML) in strukturierter HTML-Darstellung",
    # 2711: "NRSITZ (Nationalrat) oder BRSITZ (Bundesrat)", #"NRSITZ (Nationalrat) oder BRSITZ (Bundesrat)",
    # 2712: "technische Angabe", #"technische Angabe",
    # 2714: "NRSITZ (Nationalrat) oder BRSITZ (Bundesrat)", #"NRSITZ (Nationalrat) oder BRSITZ (Bundesrat)",
    # 2741: "Verlinkung auf die Geschichtsseite der Sitzung - Abschnitt Protokoll - (vorläufiges Protokoll)", #"Verlinkung auf die Geschichtsseite der Sitzung - Abschnitt Protokoll - (vorläufiges Protokoll)",
    # 202: "technische Angabe", #"technische Angabe"
    ## for global metadata header of api 251
    110: "Gremium",
    111: "GP_CODE",
    # 425: "gp_von",
    112: "Sitzung",
    113: "title",
    114: "link",
    115: "link_video",
    116: "Personen_ID",
    968: "Datum",
    3401: "Sortier",
    ## for global metadata header of api 409
    605: "Name",
    603: "Gremium",
    # 604: "WENTRY_ID",
    623: "gender",
    # 624: "gender_full",
    863: "GP_CODE",
    # 864: "Fraktionen",
    643: "_deflatable",
    903: "ist_praes",
    1223: "vorname",
    1224: "nachname",
    # 1225: "akgr",
    # 1226: "akgr_h",
    # 7120: "Fraktionen_full",
    7121: "Wahlkreis",
    7180: "PERS_URL",
    ## for automatically deflated (without "feldId")
    "pad_intern": "Personen_ID",
}

_sql_keywords = [
    "ABORT",
    "ACTION",
    "ADD",
    "AFTER",
    "ALL",
    "ALTER",
    "ALWAYS",
    "ANALYZE",
    "AND",
    "AS",
    "ASC",
    "ATTACH",
    "AUTOINCREMENT",
    "BEFORE",
    "BEGIN",
    "BETWEEN",
    "BY",
    "CASCADE",
    "CASE",
    "CAST",
    "CHECK",
    "COLLATE",
    "COLUMN",
    "COMMIT",
    "CONFLICT",
    "CONSTRAINT",
    "CREATE",
    "CROSS",
    "CURRENT",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "DATABASE",
    "DEFAULT",
    "DEFERRABLE",
    "DEFERRED",
    "DELETE",
    "DESC",
    "DETACH",
    "DISTINCT",
    "DO",
    "DROP",
    "EACH",
    "ELSE",
    "END",
    "ESCAPE",
    "EXCEPT",
    "EXCLUDE",
    "EXCLUSIVE",
    "EXISTS",
    "EXPLAIN",
    "FAIL",
    "FILTER",
    "FIRST",
    "FOLLOWING",
    "FOR",
    "FOREIGN",
    "FROM",
    "FULL",
    "GENERATED",
    "GLOB",
    "GROUP",
    "GROUPS",
    "HAVING",
    "IF",
    "IGNORE",
    "IMMEDIATE",
    "IN",
    "INDEX",
    "INDEXED",
    "INITIALLY",
    "INNER",
    "INSERT",
    "INSTEAD",
    "INTERSECT",
    "INTO",
    "IS",
    "ISNULL",
    "JOIN",
    "KEY",
    "LAST",
    "LEFT",
    "LIKE",
    "LIMIT",
    "MATCH",
    "MATERIALIZED",
    "NATURAL",
    "NO",
    "NOT",
    "NOTHING",
    "NOTNULL",
    "NULL",
    "NULLS",
    "OF",
    "OFFSET",
    "ON",
    "OR",
    "ORDER",
    "OTHERS",
    "OUTER",
    "OVER",
    "PARTITION",
    "PLAN",
    "PRAGMA",
    "PRECEDING",
    "PRIMARY",
    "QUERY",
    "RAISE",
    "RANGE",
    "RECURSIVE",
    "REFERENCES",
    "REGEXP",
    "REINDEX",
    "RELEASE",
    "RENAME",
    "REPLACE",
    "RESTRICT",
    "RETURNING",
    "RIGHT",
    "ROLLBACK",
    "ROW",
    "ROWS",
    "SAVEPOINT",
    "SELECT",
    "SET",
    "TABLE",
    "TEMP",
    "TEMPORARY",
    "THEN",
    "TIES",
    "TO",
    "TRANSACTION",
    "TRIGGER",
    "UNBOUNDED",
    "UNION",
    "UNIQUE",
    "UPDATE",
    "USING",
    "VACUUM",
    "VALUES",
    "VIEW",
    "VIRTUAL",
    "WHEN",
    "WHERE",
    "WINDOW",
    "WITH",
    "WITHOUT",
]
